#include <Expr_parser.h>
constexpr auto MAX_TERMINALS = 26;
constexpr auto MAX_STATES = 53;
static constexpr std::array<std::array<std::optional<Action>, MAX_TERMINALS>, MAX_STATES> action_table = {
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 24},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 25},
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	Action{::Expr_parser::Action::SHIFT, 26},
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 28},
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 29},
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 30},
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	Action{::Expr_parser::Action::SHIFT, 32},
	Action{::Expr_parser::Action::SHIFT, 33},
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 24},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 25},
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	Action{::Expr_parser::Action::SHIFT, 26},
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	Action{::Expr_parser::Action::SHIFT, 35},
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 30},
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 24},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 25},
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	Action{::Expr_parser::Action::SHIFT, 26},
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 36},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 24},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 25},
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	Action{::Expr_parser::Action::SHIFT, 26},
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 24},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 25},
	Action{::Expr_parser::Action::SHIFT, 9},
	Action{::Expr_parser::Action::SHIFT, 42},
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	Action{::Expr_parser::Action::SHIFT, 26},
	Action{::Expr_parser::Action::SHIFT, 1},
	Action{::Expr_parser::Action::SHIFT, 41},
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 43},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 43},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 43},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 24},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 25},
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	Action{::Expr_parser::Action::SHIFT, 26},
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	Action{::Expr_parser::Action::SHIFT, 49},
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 50},
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 24},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 25},
	Action{::Expr_parser::Action::SHIFT, 9},
	Action{::Expr_parser::Action::SHIFT, 42},
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	Action{::Expr_parser::Action::SHIFT, 26},
	Action{::Expr_parser::Action::SHIFT, 1},
	Action{::Expr_parser::Action::SHIFT, 41},
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 24},
	Action{::Expr_parser::Action::SHIFT, 51},
	Action{::Expr_parser::Action::SHIFT, 25},
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	Action{::Expr_parser::Action::SHIFT, 26},
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 24},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 25},
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	Action{::Expr_parser::Action::SHIFT, 26},
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 24},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 25},
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	Action{::Expr_parser::Action::SHIFT, 26},
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 28},
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 29},
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 24},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 25},
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	Action{::Expr_parser::Action::SHIFT, 26},
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	Action{::Expr_parser::Action::SHIFT, 30},
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
  {
	Action{::Expr_parser::Action::SHIFT, 12},
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 9},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 10},
	Action{::Expr_parser::Action::SHIFT, 11},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 1},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 2},
	std::nullopt,
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 3},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 4},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 5},
	Action{::Expr_parser::Action::SHIFT, 6},
	Action{::Expr_parser::Action::SHIFT, 7},
	std::nullopt,
	Action{::Expr_parser::Action::SHIFT, 8},
	std::nullopt,
	std::nullopt,
  },
  {
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
	std::nullopt,
  },
};
constexpr auto MAX_NONTERMINALS = 26;
static constexpr std::array<std::array<std::optional<size_t>, MAX_NONTERMINALS>, MAX_STATES> goto_table = {
  {std::make_optional(17), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(20), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(22), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(23), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(27), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(31), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(34), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(27), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(31), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(27), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(37), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(38), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(39), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(40), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(27), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(45), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(46), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(47), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(48), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(27), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(27), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(27), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(27), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(27), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(52), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::make_optional(53), std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
  {std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt},
};
static constexpr std::array<std::pair<size_t, size_t>, 36> rules_table = {
	{
	{::Expr_parser::Rules::__q2, 0},
	{::Expr_parser::Rules::expr, 1},
	{::Expr_parser::Rules::expr, 1},
	{::Expr_parser::Rules::term, 1},
	{::Expr_parser::Rules::factor, 1},
	{::Expr_parser::Rules::factor, 1},
	{::Expr_parser::Rules::expr, 1},
	{::Expr_parser::Rules::factor, 1},
	{::Expr_parser::Rules::expr, 1},
	{::Expr_parser::Rules::expr, 1},
	{::Expr_parser::Rules::factor, 1},
	{::Expr_parser::Rules::factor, 1},
	{::Expr_parser::Rules::__q2, 1},
	{::Expr_parser::Rules::main, 1},
	{::Expr_parser::Rules::factor, 1},
	{::Expr_parser::Rules::term, 1},
	{::Expr_parser::Rules::term, 1},
	{::Expr_parser::Rules::expr, 1},
	{::Expr_parser::Rules::__grp1, 0},
	{::Expr_parser::Rules::factor, 2},
	{::Expr_parser::Rules::arg_list, 2},
	{::Expr_parser::Rules::factor, 3},
	{::Expr_parser::Rules::expr, 3},
	{::Expr_parser::Rules::expr, 3},
	{::Expr_parser::Rules::expr, 3},
	{::Expr_parser::Rules::expr, 3},
	{::Expr_parser::Rules::expr, 3},
	{::Expr_parser::Rules::factor, 1},
	{::Expr_parser::Rules::power, 1},
	{::Expr_parser::Rules::power, 3},
	{::Expr_parser::Rules::term, 3},
	{::Expr_parser::Rules::term, 3},
	{::Expr_parser::Rules::expr, 3},
	{::Expr_parser::Rules::factor, 4},
	{::Expr_parser::Rules::__grp1, 3},
	{::Expr_parser::Rules::expr, 5}
	}
};
