name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Install Boost (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev gcc build-essential

      - name: Install Boost (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd ${{ github.workspace }}
          ./prepare_boost.bat
      - name: Install Ninja (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y ninja-build
      - name: Install Ninja (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          choco install ninja -y
      - name: Configure CMake (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          cmake -B build -G Ninja \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -S ${{ github.workspace }}
      - name: Configure CMake (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        shell: cmd
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\..\..\VC\Auxiliary\Build\vcvarsall.bat" amd64 && cmake -B build -G Ninja ^
          -DCMAKE_CXX_FLAGS="/I\"C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.42.34434\include\""
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} ^
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} ^
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ^
          -DBOOST_ROOT="./boost" ^
          -S "${{ github.workspace }}"
      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Test
        working-directory: build
        run: ctest --build-config ${{ matrix.build_type }}
